version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27048:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: zoo

volumes:
  mongodb_data_container: